version: "3"

services:
  api:
    build: ./api
    ports:
      - "5555:5555"
    depends_on:
      - db
    container_name: agrisults-api
    env_file: ./api/.env
    volumes: 
      - ./api:/api
    mem_limit: 128m
    links: 
      - ui
      - mongo
    

  ui:
    build: ./ui
    ports:
      - "80:3000"
    container_name: agrisults-ui
    env_file: ./ui/.env
    volumes: 
      - ./ui:/app
    mem_limit: 128m
    links:
      - api
    

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: agrisults-db
    volumes:
      - ./database:/data/db
    mem_limit: 128m
    links:
      - api
    
  